"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# ============================================================
# SETTINGS PRINCIPALES DEL BACKEND
# ------------------------------------------------------------
# Aquí viven las decisiones de infraestructura de Django:
# - apps instaladas
# - middleware
# - base de datos
# - CORS
# - configuración DRF
# ============================================================
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Load .env before reading any os.environ values
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=BASE_DIR / ".env")

# ============================================================
# [P1-12] Sentry — captura de errores y trazas de performance
# ============================================================
SENTRY_DSN = os.getenv("SENTRY_DSN", "")
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(
                transaction_style="url",
                middleware_spans=True,
                signals_spans=False,
            ),
            CeleryIntegration(monitor_beat_tasks=True),
            RedisIntegration(),
        ],
        traces_sample_rate=0.1,
        profiles_sample_rate=0.05,
        environment=os.getenv("ENVIRONMENT", "development"),
        send_default_pii=False,
        before_send=lambda event, hint: event,
    )


def parse_bool_env(var_name: str, default: bool = False) -> bool:
    value = os.getenv(var_name)
    if value is None:
        return default

    return value.strip().lower() in {"1", "true", "yes", "on"}


def parse_list_env(var_name: str, default: list[str] | None = None) -> list[str]:
    value = os.getenv(var_name)
    if not value:
        return default or []

    return [item.strip() for item in value.split(",") if item.strip()]


# [P0-1] SECRET_KEY — crash intencional si no está en el entorno
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# [P0-2] DEBUG lee del entorno; por defecto False (seguro en producción)
DEBUG = parse_bool_env("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = parse_list_env(
    "ALLOWED_HOSTS",
    # En dev (DEBUG=True) permitimos cualquier host para no tener que
    # actualizar la IP cada vez que se cambia de red WiFi al probar en
    # un dispositivo físico. En producción (DEBUG=False) el default es
    # lista vacía, forzando que ALLOWED_HOSTS venga explícito del entorno.
    default=["*"] if DEBUG else [],
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # ----- Librerías de terceros -----
    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    # ----- Nuestras apps -----
    "restaurants",
    "accounts",
    # [P1-4] django-cleanup debe ir AL FINAL para interceptar señales de borrado
    "django_cleanup.apps.CleanupConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # <-- CORS debe ir ANTES de CommonMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# ============================================================
# Base de datos: PostgreSQL
# ============================================================
# ENGINE: le dice a Django que use PostgreSQL en vez de SQLite
# NAME: nombre de la base de datos que creamos con 'createdb medeats'
# USER: tu usuario de macOS (PostgreSQL lo crea automáticamente)
# HOST: localhost porque corre en tu máquina
# PORT: 5432 es el puerto por defecto de PostgreSQL

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "medeats"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
        # [P1-11] Connection pooling — keep connections alive 10 min por worker.
        # "read committed" ya es el default de PostgreSQL, así que no hace falta
        # forzarlo explícitamente (libpq parsea mal el espacio interno).
        "CONN_MAX_AGE": 600,
        "OPTIONS": {
            "connect_timeout": 10,
        },
        "TEST": {
            "NAME": "medeats_test",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# [P1-4] Storage — S3 en producción, local en desarrollo
USE_S3 = parse_bool_env("USE_S3", default=not DEBUG)

if USE_S3:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "bucket_name": os.environ["AWS_S3_BUCKET"],
                "region_name": os.getenv("AWS_S3_REGION", "us-east-1"),
                "custom_domain": os.getenv("CLOUDFRONT_DOMAIN"),
                "default_acl": "private",
                "file_overwrite": False,
                "object_parameters": {
                    "CacheControl": "max-age=86400",
                },
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    MEDIA_URL = "https://{}/".format(
        os.getenv("CLOUDFRONT_DOMAIN") or os.getenv("AWS_S3_BUCKET", "")
    )
else:
    # Desarrollo local — comportamiento original
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# ============================================================
# [P1-1] Redis: caché y sesiones
# ============================================================
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://localhost:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "IGNORE_EXCEPTIONS": True,  # si Redis falla, la app sigue funcionando
        },
        "KEY_PREFIX": "medeats",
        "TIMEOUT": 300,  # 5 minutos por defecto
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# ============================================================
# [P1-2] Celery: tareas asíncronas (geocodificación, emails, etc.)
# ============================================================
CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================================
# CORS: Permite que React Native se conecte al backend
# ============================================================
# [P0-4] Nunca permitir todos los orígenes; lista explícita siempre.
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = parse_list_env(
    "CORS_ALLOWED_ORIGINS",
    default=(
        [
            "http://localhost:8081",
            "http://127.0.0.1:8081",
        ]
        if DEBUG
        else []
    ),
)

# ============================================================
# Django REST Framework: Configuración de la API
# ============================================================
# [P0-3] Deny by default: cualquier vista nueva que olvide declarar
# permission_classes requerirá autenticación en vez de ser pública.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "1000/day",
        "user": "10000/day",
        "login": "10/minute",
        "register": "5/hour",
        "ai_chat": "20/hour",
    },
}

# [P0-5] JWT lifetimes reducidos + rotación de refresh tokens
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}

# ============================================================
# Gemini (Foodie AI)
# ============================================================
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-1.5-flash")

# ============================================================
# [P3-4] LOGGING — texto legible en dev, JSON estructurado en prod
# ============================================================
# En producción usamos pythonjsonlogger.JsonFormatter para que Cloud
# log aggregators (Datadog, CloudWatch, GCP Logging) parseen los
# campos automáticamente.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "json": (
            {
                "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
                "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
            }
            if not DEBUG
            else {
                "format": "{levelname} {asctime} {module} {message}",
                "style": "{",
            }
        ),
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple" if DEBUG else "json",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG" if DEBUG else "INFO",
    },
    "loggers": {
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "celery": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}
