# Generated by Django 6.0.2 on 2026-03-19 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre de la categoría",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del restaurante"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Calificación",
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL de la Imagen",
                    ),
                ),
                ("latitude", models.FloatField(verbose_name="Latitud")),
                ("longitude", models.FloatField(verbose_name="Longitud")),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Ubicación/Barrio"),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "menu_highlights",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Platos Destacados"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número de WhatsApp"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restaurants",
                        to="restaurants.category",
                        verbose_name="Categoría",
                    ),
                ),
            ],
        ),
    ]
