# Generated by Django 6.0.2 on 2026-04-20 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, verbose_name="Usuario")),
                (
                    "avatar",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL del avatar"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="Calificación"
                    ),
                ),
                ("comment", models.TextField(verbose_name="Comentario")),
                ("date", models.DateField(auto_now_add=True, verbose_name="Fecha")),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="restaurants.restaurant",
                        verbose_name="Restaurante",
                    ),
                ),
            ],
        ),
    ]
