# Generated by Django 6.0.2 on 2026-04-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_post_created_at_alter_restaurant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(max_length=500, upload_to='posts/', verbose_name='Imagen/Video'),
        ),
    ]
