# Generated by Django 6.0.2 on 2026-05-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0008_alter_review_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="menu_pdf",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="menus/",
                verbose_name="Menú PDF",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_restaurants",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Propietario (cuenta restaurante)",
            ),
        ),
        migrations.CreateModel(
            name="RestaurantBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre de la sede")),
                ("address", models.CharField(max_length=255, verbose_name="Dirección")),
                ("latitude", models.FloatField(verbose_name="Latitud")),
                ("longitude", models.FloatField(verbose_name="Longitud")),
                ("is_primary", models.BooleanField(default=False, verbose_name="Sede principal")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="restaurants.restaurant",
                        verbose_name="Restaurante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede de restaurante",
                "verbose_name_plural": "Sedes de restaurantes",
                "ordering": ["-is_primary", "name"],
            },
        ),
    ]
