# Generated by Django 6.0.2 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0009_restaurant_owner_menu_pdf_restaurantbranch"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", False)),
                fields=("owner",),
                name="unique_restaurant_per_owner",
            ),
        ),
    ]
