# Generated by Django 6.0.2 on 2026-05-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0011_remove_restaurantbranch_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="restaurants/",
                verbose_name="Imagen del Restaurante",
            ),
        ),
    ]
