# Generated by Django 6.0.2 on 2026-05-19 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0012_alter_restaurant_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Acoso"),
                            ("hate_speech", "Discurso de odio"),
                            ("inappropriate_content", "Contenido inapropiado"),
                            ("misinformation", "Desinformación"),
                            ("other", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Razón del reporte",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción adicional"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("reviewed", "Revisado"),
                            ("dismissed", "Rechazado"),
                            ("actioned", "Accionado"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, verbose_name="Notas del administrador"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="restaurants.postcomment",
                        verbose_name="Comentario reportado",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="restaurants.post",
                        verbose_name="Post reportado",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reportero",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de contenido",
                "verbose_name_plural": "Reportes de contenido",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Fecha")),
                (
                    "total_users",
                    models.IntegerField(default=0, verbose_name="Total de usuarios"),
                ),
                (
                    "new_users",
                    models.IntegerField(default=0, verbose_name="Nuevos usuarios"),
                ),
                (
                    "active_users",
                    models.IntegerField(default=0, verbose_name="Usuarios activos"),
                ),
                (
                    "total_restaurants",
                    models.IntegerField(
                        default=0, verbose_name="Total de restaurantes"
                    ),
                ),
                (
                    "new_restaurants",
                    models.IntegerField(default=0, verbose_name="Nuevos restaurantes"),
                ),
                (
                    "total_posts",
                    models.IntegerField(default=0, verbose_name="Total de posts"),
                ),
                (
                    "new_posts",
                    models.IntegerField(default=0, verbose_name="Nuevos posts"),
                ),
                (
                    "total_reviews",
                    models.IntegerField(default=0, verbose_name="Total de reseñas"),
                ),
                (
                    "new_reviews",
                    models.IntegerField(default=0, verbose_name="Nuevas reseñas"),
                ),
                (
                    "total_likes",
                    models.IntegerField(default=0, verbose_name="Total de likes"),
                ),
                (
                    "total_comments",
                    models.IntegerField(default=0, verbose_name="Total de comentarios"),
                ),
                (
                    "content_reports",
                    models.IntegerField(
                        default=0, verbose_name="Reportes de contenido"
                    ),
                ),
                (
                    "posts_removed",
                    models.IntegerField(default=0, verbose_name="Posts removidos"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Analytics de la plataforma",
                "verbose_name_plural": "Analytics de la plataforma",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date",), name="unique_analytics_per_date"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PostModeration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("hidden", "Oculto"),
                            ("deleted", "Eliminado"),
                            ("flagged", "Marcado para revisión"),
                            ("restored", "Restaurado"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Acoso"),
                            ("hate_speech", "Discurso de odio"),
                            ("inappropriate_content", "Contenido inapropiado"),
                            ("misinformation", "Desinformación"),
                            ("other", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Razón de moderación",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "moderator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Moderador",
                    ),
                ),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation",
                        to="restaurants.post",
                        verbose_name="Post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderación de post",
                "verbose_name_plural": "Moderaciones de posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Crear"),
                            ("update", "Actualizar"),
                            ("delete", "Eliminar"),
                            ("moderate", "Moderar"),
                            ("restore", "Restaurar"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurante"),
                            ("post", "Post"),
                            ("comment", "Comentario"),
                            ("user", "Usuario"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de modelo",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(verbose_name="ID del objeto"),
                ),
                (
                    "object_name",
                    models.CharField(max_length=255, verbose_name="Nombre del objeto"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Cambios realizados"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario administrador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de auditoría del admin",
                "verbose_name_plural": "Logs de auditoría del admin",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["admin_user", "-timestamp"],
                        name="restaurants_admin_u_728c9f_idx",
                    ),
                    models.Index(
                        fields=["model_type", "object_id"],
                        name="restaurants_model_t_f7e0ab_idx",
                    ),
                ],
            },
        ),
    ]
