# Generated by Django 6.0.2 on 2026-05-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0013_contentreport_platformanalytics_postmoderation_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="adminauditlog",
            name="restaurants_admin_u_728c9f_idx",
        ),
        migrations.RemoveIndex(
            model_name="adminauditlog",
            name="restaurants_model_t_f7e0ab_idx",
        ),
        migrations.RemoveField(
            model_name="contentreport",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="contentreport",
            name="post",
        ),
        migrations.RemoveField(
            model_name="contentreport",
            name="reporter",
        ),
        migrations.RemoveField(
            model_name="contentreport",
            name="reviewed_by",
        ),
        migrations.RemoveConstraint(
            model_name="platformanalytics",
            name="unique_analytics_per_date",
        ),
        migrations.DeleteModel(
            name="PlatformAnalytics",
        ),
        migrations.RemoveField(
            model_name="postmoderation",
            name="moderator",
        ),
        migrations.RemoveField(
            model_name="postmoderation",
            name="post",
        ),
        migrations.RemoveField(
            model_name="adminauditlog",
            name="admin_user",
        ),
        migrations.DeleteModel(
            name="ContentReport",
        ),
        migrations.DeleteModel(
            name="PostModeration",
        ),
        migrations.DeleteModel(
            name="AdminAuditLog",
        ),
    ]
