# Generated by Django 6.0.2 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="account_type",
            field=models.CharField(
                choices=[("user", "User"), ("restaurant", "Restaurant")],
                db_index=True,
                default="user",
                max_length=20,
            ),
        ),
    ]
