# Generated by Django 6.0.2 on 2026-05-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_image",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("no_say", "Prefer not to say"),
                ],
                default="no_say",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
